"""European Accessibility Act (EAA) evidence pack generator."""
import datetime
from .models import VERSION
from .openacr import EN_301_549_MAP


def _md(value):
    s = str(value)
    s = s.replace("\\", "\\\\").replace("|", "\\|")
    s = s.replace("\n", " ").replace("\r", " ")
    return s


def generate_eaa_pack(summary, violations, client_name="Client", audit_date=""):
    today = audit_date or datetime.date.today().isoformat()

    failing = {}
    for v in violations:
        for sc in v.wcag_scs:
            failing.setdefault(sc, set()).add(v.id)

    clause_rows = []
    for sc in sorted(failing):
        clause = EN_301_549_MAP.get(sc, f"9.{sc}")
        rules = ", ".join(sorted(failing[sc])[:6])
        clause_rows.append(f"| {sc} | {clause} | AA | Does Not Support (automated) | {_md(rules)} |")
    clause_table = "\n".join(clause_rows) if clause_rows else "| - | - | - | No automated failures detected | - |"

    remediation_rows = []
    order = {"critical": 0, "serious": 1, "moderate": 2, "minor": 3}
    for v in sorted(violations, key=lambda x: order.get(x.impact, 4)):
        remediation_rows.append(
            f"| {_md(v.id)} | {_md(v.impact)} | {v.nodes} | "
            f"{_md(', '.join(v.wcag_scs) or '-')} | {_md(v.source)} | Open |"
        )
    remediation_table = "\n".join(remediation_rows) if remediation_rows else "| - | - | - | - | - | - |"

    counts = (f"(critical {summary.critical}, serious {summary.serious}, "
              f"moderate {summary.moderate}, minor {summary.minor})")

    return f"""# EAA Accessibility Evidence Pack

**Product / Website:** {_md(client_name)}
**Assessment date:** {today}
**Generated by:** AccessDoc {VERSION}
**Legal basis:** European Accessibility Act (Directive (EU) 2019/882); harmonised standard EN 301 549 (Web = Chapter 9).

> **Coverage limitation (read first).** This pack is built from an *automated*
> scan (axe-core). Automated tooling detects approximately **30-57%** of WCAG
> issues (Deque Systems 2022). It is **evidence of a conformance effort**, not a
> declaration of conformity. Full conformance requires manual and
> assistive-technology testing by a qualified evaluator.

## 1. Scope of assessment
- **Target:** {_md(summary.url or 'N/A')}
- **Evaluation method:** Automated (axe-core {_md(summary.engine_version or 'unknown')})
- **Conformance target:** EN 301 549 Chapter 9 / WCAG 2.2 Level AA
- **Automated findings:** {summary.total_violations} {counts}
- **Manual findings merged:** {summary.manual_findings}

## 2. EN 301 549 clause assessment (automated)

| WCAG SC | EN 301 549 clause | Level | Adherence | Detected by (axe rules) |
|---------|-------------------|-------|-----------|--------------------------|
{clause_table}

## 3. Remediation log

| Rule | Impact | Instances | WCAG SC | Source | Status |
|------|--------|-----------|---------|--------|--------|
{remediation_table}

## 4. Accessibility statement fields (to be completed by the provider)

- **Compliance status:** [ ] Fully compliant  [ ] Partially compliant  [ ] Non-compliant
- **Non-accessible content and reasons:** _..._
- **Feedback mechanism / contact:** _..._
- **Enforcement procedure / national authority:** _..._
- **Date of statement / last review:** {today}
- **Method used to prepare the statement:** Self-assessment assisted by AccessDoc automated evidence.

## 5. Attestation
This pack is accompanied by a tamper-evident receipt (`receipt.json`), an
EN 301 549-mapped `openacr.yaml`, and an in-toto attestation
(`attestation.intoto.json`) whose digests cover every file in this bundle.

_Generated {today} - AccessDoc {VERSION}. Not legal advice._
"""
