"""European Accessibility Act (EAA) evidence pack generator."""
import datetime
from .models import VERSION, SOURCE_AUTOMATED, SOURCE_MANUAL
from .openacr import EN_301_549_MAP, _evaluation_methods, _source_notes
from .wcag_levels import level_for


_MD_SPECIALS = "`*_[]#~"


def _md(value):
    """Neutralise user-controlled text for safe embedding in Markdown.

    Markdown renderers (GitHub, Notion, procurement portals) pass raw HTML
    through, so `<script>` in a client name would execute wherever the EAA
    pack is previewed.  We HTML-entity-escape ``& < >`` and backslash-escape
    Markdown control characters and table delimiters.  Newlines are
    flattened so a single value can never break out of its table cell.
    """
    s = str(value)
    s = s.replace("\r", " ").replace("\n", " ")
    s = s.replace("\\", "\\\\").replace("|", "\\|")
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    for ch in _MD_SPECIALS:
        s = s.replace(ch, "\\" + ch)
    return s


def generate_eaa_pack(summary, violations, client_name="Client", audit_date=""):
    today = audit_date or datetime.date.today().isoformat()

    failing = {}
    for v in violations:
        for sc in v.wcag_scs:
            failing.setdefault(sc, []).append(v)

    clause_rows = []
    for sc in sorted(failing):
        clause = EN_301_549_MAP.get(sc, "Not mapped")
        level = level_for(sc) or "Unknown"
        sources = _source_notes(failing[sc], limit=6)
        clause_rows.append(
            f"| {_md(sc)} | {_md(clause)} | {_md(level)} | Does Not Support "
            f"(draft; unreviewed) | {_md(sources)} |")
    clause_table = "\n".join(clause_rows) if clause_rows else (
        "| - | - | - | No automated failures detected; no supplied findings; "
        "not evaluated | - |")

    remediation_rows = []
    order = {"critical": 0, "serious": 1, "moderate": 2, "minor": 3}
    for v in sorted(violations, key=lambda x: order.get(x.impact, 4)):
        remediation_rows.append(
            f"| {_md(v.id)} | {_md(v.impact)} | {v.nodes} | "
            f"{_md(', '.join(v.wcag_scs) or '-')} | {_md(v.source)} | Open |"
        )
    remediation_table = "\n".join(remediation_rows) if remediation_rows else "| - | - | - | - | - | - |"

    counts = (f"(critical {summary.critical}, serious {summary.serious}, "
              f"moderate {summary.moderate}, minor {summary.minor})")
    automated_count = sum(v.source == SOURCE_AUTOMATED for v in violations)
    manual_count = sum(v.source == SOURCE_MANUAL for v in violations)
    other_count = len(violations) - automated_count - manual_count

    return f"""# EAA Accessibility Evidence Pack — DRAFT - UNREVIEWED

**Product / Website:** {_md(client_name)}
**Assessment date:** {today}
**Generated by:** AccessDoc {VERSION}
**Reference frameworks (not an applicability determination):** European Accessibility Act (Directive (EU) 2019/882); EN 301 549 (Web = Chapter 9).

> **Coverage limitation (read first).** This draft organizes supplied scanner
> evidence and any supplied manual or other observations. No reviewer approval is recorded;
> source labels do not authenticate testing, identity, or independent verification.
> Automated tooling detects approximately **30-57%** of WCAG issues (Deque Systems 2022).
> This is not evidence of conformance and not a declaration of conformity.
> Qualified review and relevant manual/assistive-technology testing remain required;
> absence of supplied findings is not evidence of conformance.

## 1. Scope of assessment
- **Target:** {_md(summary.url or 'N/A')}
- **Evaluation method:** {_md(_evaluation_methods(summary, violations))}
- **Conformance target:** EN 301 549 Chapter 9 / WCAG 2.2 Level AA
- **Total supplied findings:** {len(violations)} {counts}
- **Automated findings:** {automated_count}
- **Supplied manual findings:** {manual_count}
- **Other supplied findings:** {other_count}

## 2. EN 301 549 clause assessment (draft supplied evidence)

Draft classifications from supplied findings require qualified review; they are not approved product-wide judgments.
Levels use the repository WCAG lookup; EN clauses use its bounded explicit mapping,
not a complete or independently validated standards mapping. Unlisted clauses are
marked Not mapped; unknown criteria have Unknown level, not a guessed classification.

| WCAG SC | EN 301 549 clause | Level | Draft adherence | Supplied observation sources (unreviewed) |
|---------|-------------------|-------|-----------|--------------------------|
{clause_table}

## 3. Remediation log

| Rule | Impact | Instances | WCAG SC | Source | Status |
|------|--------|-----------|---------|--------|--------|
{remediation_table}

## 4. Accessibility statement fields (to be completed by the provider)

- **Draft compliance self-assessment (unchecked; requires qualified human evaluation):** [ ] Fully compliant  [ ] Partially compliant  [ ] Non-compliant
- **Non-accessible content and reasons:** _..._
- **Feedback mechanism / contact:** _..._
- **Enforcement procedure / national authority:** _..._
- **Date of statement / last review:** To be supplied by the provider; no review date is recorded.
- **Method used to prepare the statement:** To be completed by the provider and qualified reviewer. AccessDoc organizes supplied evidence, not an approved self-assessment.

## 5. Attestation
This pack is accompanied by a tamper-evident receipt (`receipt.json`), an
EN 301 549-mapped `openacr.yaml`, and an in-toto envelope
(`attestation.intoto.json`) whose digests identify generated artifact bytes.
Local envelopes are unsigned by default; matching digests do not establish
source truth, independent review, approval, or conformity.

_Generated {today} - AccessDoc {VERSION}. Not legal advice._
"""
