"""VPAT / ACR draft generator (WCAG edition, VPAT 2.x style).

SECURITY: every user/scan-controlled value is HTML-escaped.
"""
import html
import datetime
from .models import VERSION

_SC_NAMES = {
    "1.1.1": "Non-text Content (A)",
    "1.2.1": "Audio-only and Video-only (Prerecorded) (A)",
    "1.2.2": "Captions (Prerecorded) (A)",
    "1.3.1": "Info and Relationships (A)",
    "1.3.4": "Orientation (AA)",
    "1.3.5": "Identify Input Purpose (AA)",
    "1.4.1": "Use of Color (A)",
    "1.4.3": "Contrast (Minimum) (AA)",
    "1.4.4": "Resize Text (AA)",
    "1.4.12": "Text Spacing (AA)",
    "2.1.1": "Keyboard (A)",
    "2.1.2": "No Keyboard Trap (A)",
    "2.2.1": "Timing Adjustable (A)",
    "2.2.2": "Pause, Stop, Hide (A)",
    "2.4.1": "Bypass Blocks (A)",
    "2.4.2": "Page Titled (A)",
    "2.4.3": "Focus Order (A)",
    "2.4.4": "Link Purpose (In Context) (A)",
    "2.4.6": "Headings and Labels (AA)",
    "2.5.3": "Label in Name (A)",
    "2.5.8": "Target Size (Minimum) (AA)",
    "3.1.1": "Language of Page (A)",
    "3.1.2": "Language of Parts (AA)",
    "3.3.1": "Error Identification (A)",
    "3.3.2": "Labels or Instructions (A)",
    "4.1.1": "Parsing (A - obsolete in 2.2)",
    "4.1.2": "Name, Role, Value (A)",
}


def generate_vpat_html(summary, violations, client_name="Client", audit_date=""):
    e = html.escape
    today = audit_date or datetime.date.today().isoformat()

    failing = {}
    for v in violations:
        for sc in v.wcag_scs:
            failing.setdefault(sc, []).append(v.id)

    rows = []
    for sc, name in _SC_NAMES.items():
        if sc in failing:
            level = "Does Not Support"
            remarks = "Automated failures: " + e(", ".join(sorted(set(failing[sc]))[:6]))
        else:
            level = "Not Evaluated (automated pass / not covered)"
            remarks = "No automated failure detected. Manual verification required."
        rows.append(
            f"<tr><td>{e(sc)} {e(name)}</td><td>{level}</td><td>{remarks}</td></tr>"
        )
    table_rows = "\n".join(rows)

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>VPAT DRAFT - {e(client_name)}</title>
<style>
 body{{font-family:Arial,Helvetica,sans-serif;margin:2rem;color:#1a1a1a}}
 .draft{{background:#b30000;color:#fff;padding:.5rem 1rem;font-weight:bold;border-radius:4px;display:inline-block}}
 table{{border-collapse:collapse;width:100%;margin-top:1rem}}
 th,td{{border:1px solid #999;padding:.4rem .6rem;text-align:left;vertical-align:top;font-size:14px}}
 th{{background:#2C3E50;color:#fff}}
 .note{{color:#555;font-size:12px}}
</style></head><body>
<span class="draft">DRAFT - AUTOMATED EVIDENCE ONLY - NOT A CERTIFIED VPAT</span>
<h1>Accessibility Conformance Report (VPAT&reg; 2.x style)</h1>
<p><strong>Product:</strong> {e(client_name)}<br>
<strong>Report date:</strong> {e(today)}<br>
<strong>Evaluation method:</strong> Automated (axe-core {e(summary.engine_version or 'unknown')})<br>
<strong>Generated by:</strong> AccessDoc {e(VERSION)}</p>
<p class="note">Automated tooling detects approximately 30-57% of WCAG issues
(Deque Systems 2022). "Not Evaluated" rows are NOT claims of conformance;
they require manual and assistive-technology testing before this draft
becomes a defensible VPAT. This document is not legal advice.</p>
<h2>WCAG 2.2 Report Tables (Level A / AA)</h2>
<table>
<tr><th>Success Criterion</th><th>Conformance Level</th><th>Remarks and Explanations</th></tr>
{table_rows}
</table>
</body></html>
"""
