#!/usr/bin/env python3
"""Embed the allowlisted public/ assets into api/public_assets.py.

Why: Vercel does not ship public/ inside the Python function bundle, and
vercel.json routes every path to api/handler.py. Anything under api/ is
provably bundled (the handler itself lives there), so the hosted UI, docs and
OpenAPI document are embedded as base64 with a SHA-256 per asset. The handler
prefers the on-disk file and falls back to this module. A unit test fails when
the module is out of sync with public/ - run this script and commit.
"""
import base64
import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, "public")
OUT = os.path.join(ROOT, "api", "public_assets.py")
ASSET_FILES = (
    "index.html",
    "docs.html",
    "openapi.json",
    "static/app.css",
    "static/app.js",
    "static/report.css",
    "sample/axe-sample.json",
)
MAX_BYTES = 512 * 1024


def render():
    lines = [
        '"""GENERATED by scripts/embed_public_assets.py - do not edit by hand.',
        '',
        'Allowlisted public/ assets for the serverless adapter (Vercel does not bundle',
        'public/ into the Python function). Keys are paths relative to public/.',
        '"""',
        'import base64',
        '',
        'ASSETS = {',
    ]
    for rel in ASSET_FILES:
        with open(os.path.join(PUBLIC, *rel.split("/")), "rb") as fh:
            data = fh.read()
        if len(data) > MAX_BYTES:
            raise SystemExit(f"{rel} exceeds {MAX_BYTES} bytes")
        b64 = base64.b64encode(data).decode("ascii")
        chunks = [b64[i:i + 76] for i in range(0, len(b64), 76)] or [""]
        lines.append(f'    {rel!r}: ("{hashlib.sha256(data).hexdigest()}", (')
        for c in chunks:
            lines.append(f'        "{c}"')
        lines.append("    )),")
    lines += [
        "}",
        "",
        "",
        "def load(rel):",
        '    """Return the asset bytes for a public/-relative path, or None."""',
        "    entry = ASSETS.get(rel)",
        "    if not entry:",
        "        return None",
        '    return base64.b64decode("".join(entry[1]))',
        "",
    ]
    return "\n".join(lines)


def main(argv):
    text = render()
    if "--check" in argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("api/public_assets.py is out of sync with public/; run scripts/embed_public_assets.py")
            return 1
        print("public assets in sync")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {OUT} ({len(text)} chars, {len(ASSET_FILES)} assets)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
